config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for  :users,
              :path => '',
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {
                                :omniauth_callbacks => 'omniauth_callbacks',
                                :registrations => 'registrations'
                              }

  resources :users, only: [:show]
  resources :spaces
  resources :photos
  resources :spaces do
    resources :bookings, only: [:create]
  end

  resources :spaces do
    resources :reviews, only: [:create, :destroy]
  end

  get '/preload' => 'bookings#preload'
  get '/preview' => 'bookings#preview'

  get '/your_bookings' => 'bookings#your_bookings'
  get '/your_events' => 'bookings#your_events'

  post '/notify' => 'bookings#notify'
  post '/your_events' => 'bookings#your_events'

  get '/search' => 'pages#search'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :space
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, except: [:notify]


  def preload
    space = Space.find(params[:space_id])
    today = Date.today
    bookings = space.bookings.where("start_date >= ? OR end_date >= ?", today, today)

    render json: bookings
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date)
    }

    render json: output
  end

  def create
=begin trying to check if user is the space owner, can't access the booked space id
    current_user.spaces.each do |space|
      #value: @space.id
      if space.id == booking_params.fifth
        redirect_to space, alert: "Your booking has failed..."
        return false
      end
    end
=end
    @booking = current_user.bookings.create(booking_params)

    if @booking
      #send request to Paypal
      values = {
        business: 'mdas.rafael-facilitator@gmail.com',
        cmd: '_xclick',
        upload: 1,
        notify_url: 'http://322c2da9.ngrok.io/notify',
        amount: @booking.total,
        item_name: @booking.space.space_name,
        item_number: @booking.id,
        quantity: '1',
        return: 'http://322c2da9.ngrok.io/your_events'
      }

      redirect_to "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query, notice: "Your booking has been registered..."
    else
      redirect_to @booking.space, alert: "Oops, something went wrong..."
    end
  end

  protect_from_forgery except: [:notify]
  def notify
    params.permit!
    status = params[:payment_status]

    booking = Booking.find(params[:item_number])

    if status = "Completed"
      booking.update_attributes status:true
    else
      booking.destroy
    end

    render nothing: true
  end

  def your_bookings
    @space = current_user.spaces
  end

  protect_from_forgery except: [:your_events]
  def your_events
    @events = current_user.bookings.where("status = ?", true)
  end

  private

    def is_conflict(start_date, end_date)
      space = Space.find(params[:space_id])

      check = space.bookings.where("? < start_date AND end_date < ?", start_date, end_date)
      check.size > 0? true : false
    end

    def booking_params
      params.require(:booking).permit(:start_date, :end_date, :price, :total, :space_id)
    end
end

app/views/bookings/_form.html.erb
<%= form_for([@space, @space.bookings.new]) do |f| %>

  <div class="row">
    <div class="col-md-12 price_tag">
      <span>HK$<%= @space.price %></span>
      <span class="pull-right">Per Day</span>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <label>Check In</label>
      <%= f.text_field :start_date, readonly: 'true', placeholder: 'Start Date', class: 'form-control' %>
    </div>
    <div class="col-md-6">
      <label>Check Out</label>
      <%= f.text_field :end_date, readonly: 'true', placeholder: 'End Date', class: 'form-control', disabled: 'true' %>
    </div>
  </div>

  <%= f.hidden_field :space_id, value: @space.id %>
  <%= f.hidden_field :price, value: @space.price %>
  <%= f.hidden_field :total, id: 'booking_total' %>

  <h4><span id="message"></span></h4>

  <div id="preview" style="display: none">
    <table class="booking-table">
      <tbody>
        <tr>
          <td>Day(s)</td>
          <td><span id="booking_days"></span></td>
        </tr>
        <tr>
          <td>Total</td>
          <td>HK$<span id="booking_sum"></span></td>
        </tr>
      </tbody>
    </table>
    <br>
  </div>

  <%= f.submit "Book Now", id: "btn_book", class: "btn btn-primary wide", disabled: 'true' %>

<% end %>

<script>

  function unavailable(date) {
    dmy = date.getDate() + "-" + (date.getMonth()+1) + "-" + date.getFullYear();
    return [$.inArray(dmy, unavailableDates) == -1];
  }

  $(function() {

    unavailableDates = [];

    $.ajax({
      url: '/preload',
      data: {'space_id': <%= @space.id %>},
      dataType: 'json',
      success: function(data) {
        $.each(data, function(arrID, arrValue) {
          for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
            unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
          }
        });

        $('#booking_start_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: unavailable,
          onSelect: function(selected) {
            $('#booking_end_date').datepicker("option", "minDate", selected);
            $('#booking_end_date').attr("disabled", false);

            var start_date = $(this).datepicker('getDate');
            var end_date = $('#booking_end_date').datepicker('getDate');
            var days = (end_date - start_date)/1000/60/60/24 + 1;

            var input = {
              'start_date': start_date,
              'end_date': end_date,
              'space_id': <%= @space.id %>
            }

            $.ajax({
              url: "/preview",
              data: input,
              success: function(data) {

                if (data.conflict) {

                  $('#message').text("This date range is not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);

                } else {

                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = days * <%= @space.price %>
                  $('#booking_days').text(days);
                  $('#booking_sum').text(total);
                  $('#booking_total').val(total);
                }
              }
            });
          }
        });

        $('#booking_end_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: unavailable,
          onSelect: function(selected) {
            $('#booking_start_date').datepicker("option", "maxDate", selected);

            var start_date = $('#booking_start_date').datepicker('getDate');
            var end_date = $(this).datepicker('getDate');
            var days = (end_date - start_date)/1000/60/60/24 + 1;

            var input = {
              'start_date': start_date,
              'end_date': end_date,
              'space_id': <%= @space.id %>
            }

            $.ajax({
              url: "/preview",
              data: input,
              success: function(data) {

                if (data.conflict) {

                  $('#message').text("This date range is not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);

                } else {

                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = days * <%= @space.price %>
                  $('#booking_days').text(days);
                  $('#booking_sum').text(total);
                  $('#booking_total').val(total);
                }
              }
            });
          }
        });
      }
    });
  });
</script>

app/views/bookings/your_bookings.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Spaces", spaces_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Bookings", your_bookings_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Events", your_events_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your Bookings
      </div>
      <div class="panel-body">
        <% @space.each do |space| %>

          <% space.bookings.each do |booking| %>
            <% if booking.status %>
              <div class="row">
                <div class="col-md-2">
                  <%= booking.start_date.strftime('%v') %>
                </div>
                <div class="col-md-6">
                  <%= link_to space_path(booking.space) do %>
                    <%= image_tag booking.space.photos[0].image.url(:thumb) %>
                  <% end %>
                </div>
                <div class="col-md-2">
                  <%= link_to user_path(booking.user) do %>
                    <%= image_tag avatar_url(booking.user), class: "img-circle avatar-medium" %>
                  <% end%>
                </div>
                <div class="col-md-2 right">
                  <h4>HK$ <%= booking.total %></h4>
                </div>
              </div>
              <hr>
            <% end %>
          <% end %>

        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/bookings/your_events.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Spaces", spaces_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Bookings", your_bookings_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Events", your_events_path, class: "sidebar-link active" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your Events
      </div>
      <div class="panel-body">
        <% @events.each do |event| %>
          <div class="row">
            <div class="col-md-2">
              <%= event.start_date.strftime('%v') %>
            </div>
            <div class="col-md-6">
              <%= link_to space_path(event.space) do %>
                <%= image_tag event.space.photos[0].image.url(:thumb) %>
              <% end %>
            </div>
            <div class="col-md-2">
              <%= link_to user_path(event.space.user) do %>
                <%= image_tag avatar_url(event.space.user), class: "img-circle avatar-medium" %>
              <% end%>
            </div>
            <div class="col-md-2 right">
              <h4>HK$ <%= event.total %></h4>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>